server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: keycloak
          uri: https://github.com/alejandroDes16/microservices
          search-paths: config-data
  application:
    name: config-service

